server:
  error:
    include-stacktrace: always


 #06/12/2021 Add Database Dependecy
spring:
  application:
    name: springboot2-essentials
  datasource:
    url: jdbc:mysql://localhost:3306/anime?&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: false
#    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    health:
      show-details: when_authorized


info:
  app: Spring Boot 2 Essentials By Joujou
  website: https://joaomarcus.com.br
  github: https://github.com/joaomarcuscardoso/springboot-2-essentials