server:
  error:
    include-stacktrace: on_param


 #06/12/2021 Add Database Dependecy
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
